include: package:flutter_lints/flutter.yaml

# Additional rules can be added here
linter:
  rules:
    # Enforce good practices
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    
    # Documentation
    public_member_api_docs: false # Set to true if you want to enforce documentation
    
    # Style
    always_declare_return_types: true
    prefer_single_quotes: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
