name: flutter_login
description: A customizable Flutter login component for easy integration into Flutter applications.
version: 1.0.0
homepage: https://github.com/davideloddeDev/flutter-login

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
